<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6cd53400e6383e07fb1f963bcc202063
{
    public static $files = array (
        '25072dd6e2470089de65ae7bf11d3109' => __DIR__ . '/..' . '/symfony/polyfill-php72/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Php72\\' => 23,
            'Symfony\\Component\\WebLink\\' => 26,
            'Symfony\\Component\\Asset\\' => 24,
        ),
        'P' => 
        array (
            'Psr\\Link\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Php72\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php72',
        ),
        'Symfony\\Component\\WebLink\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/web-link',
        ),
        'Symfony\\Component\\Asset\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/asset',
        ),
        'Psr\\Link\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/link/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6cd53400e6383e07fb1f963bcc202063::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6cd53400e6383e07fb1f963bcc202063::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
