<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Symfony\\Polyfill\\Php72\\' => array($vendorDir . '/symfony/polyfill-php72'),
    'Symfony\\Component\\WebLink\\' => array($vendorDir . '/symfony/web-link'),
    'Symfony\\Component\\Asset\\' => array($vendorDir . '/symfony/asset'),
    'Psr\\Link\\' => array($vendorDir . '/psr/link/src'),
);
