services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ssch\Typo3Encore\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/ValueObject'
      - '../Classes/Asset/EntrypointLookup.php'
