name: PHP Linter

on:
    pull_request: null
    push:
        branches:
            - "master"

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-master"

jobs:
    php_linter:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [ 7.4, 8.0, 8.1 ]
        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php-versions }}"
                    coverage: none

            # see https://github.com/ramsey/composer-install
            -   uses: "ramsey/composer-install@v2"

            -   run: composer lint
